# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Realizar analisis con flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Prueba con pytest
      run: |
        python -m pytest -v --cov=. --cov-report=html --html=report.html
        
    - name: Build Clase
      run: |
        mkdir build
        cp calculadora.py build/
    - name: Build Reporte COV
      run: |
        cp -r htmlcov build/
        
    - name: Build Reporte HTML
      run: |
        cp -r assets build/
        cp -r report.html build/
    - name: Build Artefacto ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Artefacto-Probado
        path: build/
        
    
